### ISSUE TITLE
download.py missing from data_loader

### ISSUE THREAD

**Issue by samarth4149** [asrafulashiq/transfer_broad#1]
Hi, the file mentioned in the title seems missing. It is needed to download kaokore dataset. Please add it to the repo if it was missed.

Thanks.

**Comment by asrafulashiq** [comment]
Thanks for letting know. In the meantime, you can use this repo to download Kaokore: https://github.com/rois-codh/kaokore
Please use the `download.py` file.

**Comment by samarth4149** [comment]
Got it, thanks
