### ISSUE TITLE
eurosat.zip cannot be found on google drive

### ISSUE THREAD

**Issue by Cohesion97** [asrafulashiq/transfer_broad#2]
eurosat.zip cannot be found on google drive with the url: https://drive.google.com/uc?id=1FYZvuBePf2tuEsEaBCsACtIHi6eFpSwe

Can you please check the url? Thank you.

**Comment by asrafulashiq** [comment]
Hi! Thanks for letting know. I have updated the script for downloading EuroSAT. Please use the following commands:
```
wget http://madm.dfki.de/files/sentinel/EuroSAT.zip
unzip EuroSAT.zip
mkdir EuroSAT
mv -f 2750 EuroSAT
rm EuroSAT.zip

```

**Comment by Cohesion97** [comment]
Thanks for updating. It is now working
